### ISSUE TITLE
Add a specialized `CatchPanicLayer` to support presenting HTTP 500 as RFC-7807

### ISSUE THREAD

**Issue by czocher** [sazzer/problemdetails#4]
Currently if an axum handler panics, the resulting response will not be RFC-7807 compatible. I suggest to either:
1. Create an example (or updating the existing one) with a [`CatchPanicLayer`](https://docs.rs/tower-http/latest/tower_http/catch_panic/index.html) implementation presenting the panic as a RFC-7807 compatible response.
2. Providing a RFC-7807-compliant `CatchPanicLayer` as part of this library since it's probably gonna be useful for all potential users.

@sazzer I can provide a PR implementing this. Which version would you prefer though - an example (or updating the existing one) or a `CatchPanicLayer` hidden behind the `axum` feature flag?

**Comment by sazzer** [comment]
I didn't even know this was a thing! :)

Assuming that it's optional, I think your option 2 is probably the better choice. People would then be able to use it if they so desire - which is less work for them - or else they can use it as a basis for writing their own if they want to have the output look differently.

Cheers
